#ifndef CPP_30DAYMAKECPPSERVER_DAY13_SRC_INCLUDE_UTIL_H_
#define CPP_30DAYMAKECPPSERVER_DAY13_SRC_INCLUDE_UTIL_H_

void errif(bool, const char *);

#endif // CPP_30DAYMAKECPPSERVER_DAY13_SRC_INCLUDE_UTIL_H_
