// 这是在说明我们使用的是proto语法
syntax = "proto3";

// 这部分的内容是关于最后生成的cpp文件是处在哪个目录哪个包（或者命名空间）中
// .代表在当前目录生成，service代表了生成的cpp文件的命名空间是service
// option cpp_package = ".;service";

// protobuf 自身的包名
package helloworld;

// 然后我们需要定义一个服务，在这个服务中需要有一个方法，这个方法可以接受客户端的参数，再返回服务端响应。
// 其实很容易可以看出，我们定义了一个service，称为Greeter，这个服务中有一个rpc方法，名为SayHello。
// 这个方法会发送一个HelloRequest，然后返回一个HelloReply。
service Greeter {
  // Sends a greeting
  rpc SayHello (HelloRequest) returns (HelloReply) {}
}

// message关键字，可以理解为c++中的结构体。
// 这里比较特殊的是变量后面的"赋值"。注意，这里并不是赋值，而是在定义这个变量在这个message中的位置。
message HelloRequest {
  string name = 1;
//   int64 age = 2;
}

// The response message containing the greetings
message HelloReply {
  string message = 1;
}