#ifndef CPP_30DAYMAKECPPSERVER_DAY14_SRC_INCLUDE_UTIL_H_
#define CPP_30DAYMAKECPPSERVER_DAY14_SRC_INCLUDE_UTIL_H_

void ErrorIf(bool condition, const char *msg);

#endif // CPP_30DAYMAKECPPSERVER_DAY13_SRC_INCLUDE_UTIL_H_
